[general]
working_directory = "C:\\Users\\eirae\\"
live_config_reload = true

[window]
opacity = 0.95

[font]
size = 11.8
normal = { family = "FantasqueSansM Nerd Font", style = "Regular" }
bold = { family = "FantasqueSansM Nerd Font", style = "Regular" }
italic = { family = "FantasqueSansM Nerd Font", style = "Italic" }
bold_italic = { family = "FantasqueSansM Nerd Font", style = "Italic" }
builtin_box_drawing = false

[colors]
transparent_background_colors = true
cursor = { text = "#1E1E2E", cursor = "#ebdbb2" }
selection = { text = "#e0e1dd", background = "#575757" }
primary = { foreground = "#ebdbb2", background = "#0C0D0C", dim_foreground = "#828482", bright_foreground = "None" }
normal = { black = "#45475A", red = "#db7d97", green = "#A6E3A1", yellow = "#e0cb9e", blue = "#b993ba", magenta = "#F5C2E7", cyan = "#c83434", white = "#5a5a5a" }
bright = { black = "#45475A", red = "#db7d97", green = "#A6E3A1", yellow = "#e0cb9e", blue = "#b993ba", magenta = "#F5C2E7", cyan = "#c83434", white = "#5a5a5a" }
dim = { black = "#0f0f0f", red = "#712b2b", green = "#5f6f3a", yellow = "#a17e4d", blue = "#456877", magenta = "#704d68", cyan = "#4d7770", white = "#8e8e8e" }

[cursor]
vi_mode_style = { shape = "Block", blinking = "Off" }

[selection]
save_to_clipboard = true

[terminal]
shell = { program = "powershell.exe", args = ["-nologo"] }
