"$schema" = "https://raw.githubusercontent.com/rszyma/kanata-tray/main/doc/config_schema.json"

general.allow_concurrent_presets = false
defaults.tcp_port = 5829

[defaults.hooks]

[defaults.layer_icons]

[presets.'Default Preset']
kanata_executable = ''
kanata_config = '~/.config/kanata/config.kbd'
autorun = true
